// <auto-generated />
using System;
using HillMetrics.MIND.Infrastructure.Database.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HillMetrics.MIND.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MindApplicationContext))]
    [Migration("20250514185919_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DtInsert")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_insert");

                    b.Property<DateTime>("DtUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_update");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientFluxPriorityEntity", b =>
                {
                    b.Property<int>("ClientFluxRuleEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("client_flux_rule_entity_id");

                    b.Property<int>("FluxId")
                        .HasColumnType("integer")
                        .HasColumnName("flux_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("ClientFluxRuleEntityId", "FluxId")
                        .HasName("pk_clients_flux_priorities");

                    b.ToTable("clients_flux_priorities", (string)null);
                });

            modelBuilder.Entity("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientFluxRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("DtInsert")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_insert");

                    b.Property<DateTime>("DtUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_update");

                    b.Property<int>("FinancialDataPointId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_data_point_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PeerGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("peer_group_id");

                    b.Property<int>("Ranking")
                        .HasColumnType("integer")
                        .HasColumnName("ranking");

                    b.HasKey("Id")
                        .HasName("pk_clients_flux_rules");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_clients_flux_rules_client_id");

                    b.ToTable("clients_flux_rules", (string)null);
                });

            modelBuilder.Entity("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientFluxPriorityEntity", b =>
                {
                    b.HasOne("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientFluxRuleEntity", "ClientFluxRuleEntity")
                        .WithMany("FluxPriorities")
                        .HasForeignKey("ClientFluxRuleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clients_flux_priorities_clients_flux_rules_client_flux_rule");

                    b.Navigation("ClientFluxRuleEntity");
                });

            modelBuilder.Entity("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientFluxRuleEntity", b =>
                {
                    b.HasOne("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientEntity", "Client")
                        .WithMany("FluxRules")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clients_flux_rules_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientEntity", b =>
                {
                    b.Navigation("FluxRules");
                });

            modelBuilder.Entity("HillMetrics.MIND.Infrastructure.Contracts.Entity.Clients.ClientFluxRuleEntity", b =>
                {
                    b.Navigation("FluxPriorities");
                });
#pragma warning restore 612, 618
        }
    }
}
