name: SyncFromOrigin

on:
  schedule:
    - cron: '30 7 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ vars.SYNC_BRANCH }}

      - name: Sync from remote origin
        run: |
          git checkout ${{ vars.SYNC_BRANCH }}
          git pull
          git branch -vv
          git remote add sot-origin ${{ secrets.SYNC_ORIGIN_URL }}
          git fetch sot-origin
          git branch -u sot-origin/${{ vars.SYNC_BRANCH }}
          git fetch sot-origin
          git branch -u sot-origin/${{ vars.SYNC_BRANCH }}
          git pull
          git branch -u origin/${{ vars.SYNC_BRANCH }}
          git push
